#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
git secrets --scan
vendor/bin/phpstan analyse --configuration phpstan.neon --memory-limit=-1
tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --dry-run --diff
